import { FieldMetadataType } from 'twenty-shared/types';

import { type FieldMetadataSeed } from 'src/engine/workspace-manager/dev-seeder/metadata/types/field-metadata-seed.type';

export const BUSINESS_DOCUMENT_CUSTOM_FIELD_SEEDS: FieldMetadataSeed[] = [
  {
    type: FieldMetadataType.SELECT,
    name: 'docType',
    label: 'Document Type',
    icon: 'IconFileInvoice',
    options: [
      { label: 'Devis', value: 'DEVIS', position: 0, color: 'blue' },
      {
        label: 'Bon de Commande',
        value: 'BON_COMMANDE',
        position: 1,
        color: 'turquoise',
      },
      {
        label: 'Bon de Livraison',
        value: 'BON_LIVRAISON',
        position: 2,
        color: 'purple',
      },
      { label: 'Facture', value: 'FACTURE', position: 3, color: 'green' },
    ],
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'reference',
    label: 'Reference',
    icon: 'IconHash',
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'externalReference',
    label: 'External Reference',
    icon: 'IconExternalLink',
  },
  {
    type: FieldMetadataType.DATE,
    name: 'date',
    label: 'Date',
    icon: 'IconCalendar',
  },
  {
    type: FieldMetadataType.DATE,
    name: 'dueDate',
    label: 'Due Date',
    icon: 'IconCalendarDue',
  },
  {
    type: FieldMetadataType.DATE,
    name: 'deliveryDate',
    label: 'Delivery Date',
    icon: 'IconTruck',
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'companyName',
    label: 'Company Name',
    icon: 'IconBuilding',
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'companyType',
    label: 'Company Type',
    icon: 'IconUsers',
    options: [
      { label: 'Client', value: 'CLIENT', position: 0, color: 'blue' },
      { label: 'Supplier', value: 'SUPPLIER', position: 1, color: 'orange' },
    ],
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'status',
    label: 'Status',
    icon: 'IconCircleDot',
    options: [
      { label: 'Brouillon', value: 'BROUILLON', position: 0, color: 'gray' },
      { label: 'Valid\u00e9', value: 'VALIDE', position: 1, color: 'blue' },
      { label: 'Envoy\u00e9', value: 'ENVOYE', position: 2, color: 'sky' },
      {
        label: 'Accept\u00e9',
        value: 'ACCEPTE',
        position: 3,
        color: 'green',
      },
      { label: 'Refus\u00e9', value: 'REFUSE', position: 4, color: 'red' },
      {
        label: 'Factur\u00e9',
        value: 'FACTURE',
        position: 5,
        color: 'turquoise',
      },
      { label: 'Pay\u00e9', value: 'PAYE', position: 6, color: 'green' },
    ],
    defaultValue: "'BROUILLON'",
  },
  {
    type: FieldMetadataType.SELECT,
    name: 'currencyCode',
    label: 'Currency',
    icon: 'IconCurrencyDollar',
    options: [
      { label: 'TND', value: 'TND', position: 0, color: 'green' },
      { label: 'EUR', value: 'EUR', position: 1, color: 'blue' },
      { label: 'USD', value: 'USD', position: 2, color: 'sky' },
      { label: 'GBP', value: 'GBP', position: 3, color: 'purple' },
    ],
    defaultValue: "'TND'",
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'exchangeRate',
    label: 'Exchange Rate',
    icon: 'IconArrowsExchange',
    defaultValue: 1,
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'paymentTerms',
    label: 'Payment Terms',
    icon: 'IconCalendarStats',
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'paymentConditions',
    label: 'Payment Conditions',
    icon: 'IconCreditCard',
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'subtotalHt',
    label: 'Subtotal HT',
    icon: 'IconMathFunction',
    defaultValue: 0,
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'totalDiscount',
    label: 'Total Discount',
    icon: 'IconDiscount',
    defaultValue: 0,
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'totalTva',
    label: 'Total TVA',
    icon: 'IconReceipt2',
    defaultValue: 0,
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'totalTtc',
    label: 'Total TTC',
    icon: 'IconCalculator',
    defaultValue: 0,
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'timbreFiscal',
    label: 'Timbre Fiscal',
    icon: 'IconStamp',
    defaultValue: 0,
  },
  {
    type: FieldMetadataType.NUMBER,
    name: 'netAPayer',
    label: 'Net \u00e0 Payer',
    icon: 'IconCash',
    defaultValue: 0,
  },
  {
    type: FieldMetadataType.RICH_TEXT,
    name: 'notes',
    label: 'Notes',
    icon: 'IconNote',
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'project',
    label: 'Project',
    icon: 'IconBriefcase',
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'rep',
    label: 'Sales Rep',
    icon: 'IconUser',
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'pdfStoragePath',
    label: 'PDF Path',
    icon: 'IconFileTypePdf',
  },
  {
    type: FieldMetadataType.DATE,
    name: 'validatedAt',
    label: 'Validated At',
    icon: 'IconCircleCheck',
  },
  {
    type: FieldMetadataType.TEXT,
    name: 'validatedBy',
    label: 'Validated By',
    icon: 'IconUserCheck',
  },
];
